version: '3.1'
services:
  postgres:
    image: 'postgres:alpine'
    volumes:
    - postgres-volume:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres

  keycloak:
    image: jboss/keycloak
    ports:
    - 18443:8443
    - 18080:8080
    - 19990:9990
    depends_on:
      - postgres
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      POSTGRES_PORT_5433_TCP_ADDR: 127.0.0.1

  prometheus:
    image: prom/prometheus
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus-volume:/etc/prometheus
    ports:
    - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana
    volumes:
    - grafana-volume:/var/lib/grafana
    ports:
    - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - backend

volumes:
  postgres-volume:
  grafana-volume:
  prometheus-volume:

networks:
  backend:
    driver: bridge
